name: player_ahs_ir
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  audioplayers: ^6.1.2
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  path_provider: ^2.1.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
